rootProject.name = 'aviqr-backend'

include(
    'service-registry',
    'api-gateway',
    'auth-service',
    'shop-service',
    'menu-service',
    'order-service',
    'payment-service',
    'qr-service',
    'notification-service',
    'hotel-service',
    'mall-service',
    'support-service',
    'report-service',
    'ocr-service'
)
