package in.aviqr.support.service;

import in.aviqr.support.entity.Lead;
import in.aviqr.support.entity.LeadEmail;
import in.aviqr.support.entity.LeadStatus;
import in.aviqr.support.repository.LeadEmailRepository;
import in.aviqr.support.repository.LeadRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

// Phase 2 of the Lead CRM: auto-drafts follow-up emails on a fixed cadence for
// leads that went quiet after being contacted. This ONLY ever creates DRAFT
// LeadEmail rows — LeadController.sendEmail() is still the sole path anything
// reaches an inbox through, and that still requires a staff member to click
// Send on this exact draft. A lead that responded (status != CONTACTED), was
// marked DO_NOT_CONTACT/DECLINED/CONVERTED, or already has an unreviewed draft
// sitting in its queue is left alone — this never nags past two follow-ups
// or piles a second draft on top of one nobody has looked at yet.
@Service @RequiredArgsConstructor @Slf4j
public class LeadFollowUpScheduler {

    private static final int FOLLOWUP_1_AFTER_DAYS = 4; // since initial contact
    private static final int FOLLOWUP_2_AFTER_DAYS = 6; // since follow-up 1
    private static final int MAX_STAGE = 2;

    private final LeadRepository leadRepo;
    private final LeadEmailRepository emailRepo;

    @Scheduled(cron = "0 0 9 * * *") // 9 AM daily
    @Transactional
    public void generateFollowUps() {
        LocalDateTime now = LocalDateTime.now();
        int drafted = 0;
        drafted += draftForStage(0, now.minusDays(FOLLOWUP_1_AFTER_DAYS));
        drafted += draftForStage(1, now.minusDays(FOLLOWUP_2_AFTER_DAYS));
        if (drafted > 0) log.info("Auto-drafted {} lead follow-up email(s)", drafted);
    }

    private int draftForStage(int stage, LocalDateTime cutoff) {
        List<Lead> candidates = leadRepo.findByStatusAndFollowUpStageAndLastContactedAtBefore(
            LeadStatus.CONTACTED, stage, cutoff);
        int count = 0;
        for (Lead lead : candidates) {
            if (lead.getEmail() == null || lead.getEmail().isBlank()) continue;
            if (emailRepo.existsByLeadIdAndStatus(lead.getId(), in.aviqr.support.entity.LeadEmailStatus.DRAFT)) continue;

            int nextStage = stage + 1;
            String[] draft = buildFollowUp(lead, nextStage);
            emailRepo.save(LeadEmail.builder()
                .leadId(lead.getId())
                .subject(draft[0])
                .body(draft[1])
                .createdBy("system:followup-scheduler")
                .autoGenerated(true)
                .build());

            lead.setFollowUpStage(Math.min(nextStage, MAX_STAGE));
            leadRepo.save(lead);
            count++;
        }
        return count;
    }

    // Plain template, not an LLM call — there's no reusable backend AI service
    // to call today (AviQR's AI Hub features proxy straight from the frontend
    // through api-gateway's /api/v1/ai/** route to Anthropic; support-service
    // has no Anthropic client of its own). A staff member reviews and can
    // freely rewrite this before it's ever sent, so a template is sufficient
    // here rather than standing up a new LLM integration for it.
    private String[] buildFollowUp(Lead lead, int stageNumber) {
        String name = lead.getContactName() != null && !lead.getContactName().isBlank()
            ? lead.getContactName() : lead.getBusinessName();
        if (stageNumber == 1) {
            return new String[]{
                "Following up — AviQR for " + lead.getBusinessName(),
                "Hi " + name + ",\n\n" +
                "Just following up on my earlier note about AviQR — QR ordering, digital menus, and billing " +
                "in one app for " + lead.getBusinessName() + ".\n\n" +
                "Happy to answer any questions, or set up a quick walkthrough if that's easier than email. " +
                "The Starter plan is free to try, no card required.\n\n" +
                "— The AviQR Team"
            };
        }
        return new String[]{
            "One more note — AviQR for " + lead.getBusinessName(),
            "Hi " + name + ",\n\n" +
            "Didn't want to keep following up without a real reason, so this will be my last note for now. " +
            "If AviQR isn't the right fit at the moment, no worries at all — feel free to let me know and I'll " +
            "stop reaching out.\n\n" +
            "If timing is just off, the offer stands whenever you're ready: aviqr.com/register.\n\n" +
            "— The AviQR Team"
        };
    }
}
