package in.aviqr.support.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;
import java.util.UUID;

// One drafted/sent email against a Lead. Sending always requires a staff member
// to hit the /send endpoint on a specific row here — auto-drafting (Phase 2's
// LeadFollowUpScheduler) only ever creates DRAFT rows, never SENT ones.
@Entity @Table(name = "lead_emails")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class LeadEmail {
    @Id @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(nullable = false)
    private UUID leadId;

    @Column(nullable = false) private String subject;
    @Column(nullable = false, length = 8000) private String body;

    @Enumerated(EnumType.STRING)
    @Builder.Default
    private LeadEmailStatus status = LeadEmailStatus.DRAFT;

    private String createdBy;
    private String sentBy;
    private LocalDateTime sentAt;

    // True only for rows LeadFollowUpScheduler generated — lets the UI label
    // them "Suggested follow-up" and lets the scheduler tell its own drafts
    // apart from ones staff wrote by hand.
    @Builder.Default
    private Boolean autoGenerated = false;

    @CreationTimestamp private LocalDateTime createdAt;
}
